language: node_js
node_js:
- '0.10'
script: 
    #- node_modules/karma/bin/karma start karma.conf.js --single-run
- node_modules/karma/bin/karma start karma-browserstack.conf.js --single-run
- gulp lint;
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start          ;
  fi
os:
- linux
before_script:
- npm install
notifications:
  slack:
    rooms:
    - yesgraph:Ozpbr6IIOfkmUjw79ZPrOC6d#general
env:
  global:
  - secure: MK4RfNzeZgUn/Y2RNNncBDvpjZK6DupXTM6+Jl9VSEK/Usc5//0YlKueUWnVR0asH7dIPEehcBVhZHQpoB19OaPFhHHsPJIPVy+jp/LsSQSXmwjv3jGuxBv40QR6RvxmPNUH27xAOurWuM0FDfD2Wbv1npFo4GXOn1AXMFkT9UpkLu4rNrpfNCkdZq4tRU4rY/SpkvllEhzKxP4gQpVC1/EiXmtz2/AV7Sl6NvQ43A7ArXcBckIsr7vns9f4665nHagOm5GTCDichsKsF5pUapJQEG2SR/hTUSmcNbLWKrdSPW9vsb+eE18zqL3A2dpZCBtxdWvpSqYuntb8A69aPDyPEw4kgaez3ahUVxl21EiePIUR7DsUdXivx79EHZ9NiDRzgTH8KKn2siXqBGuWKibjRPNyXE8v6lx+MKYY7tdxysFJb21mEfJ/xOHnjugEbWm3Jf3fAyN3XxqGzxz2G6Xenw4Tvk1pVcCTV9BByU38CU4uaFH9XgOQBKgz4pptlOPgJrHIEd1BsO0EEHBnMT81N9lVPN2kV7oQnX8+hYh9Zl8gFHJCFXLMeRqAdKq727jH67QILOjzxO2TI1ihw9a/yOKRBzu1vgVT44X7hm7tAgm3rJn/cGaoUUFB92BAW3kiIDXcL1aAR4jXYHvZ7WxtJjN3cV6E9/ux6bkrzdA
  - secure: bV8YamG2qkrDkwC/9rR8oaaHi7KI6eta5WM2aFvaDLXB/iPsLQCA0Jw4+v/RtyDhS+l4MSLbWCtxzHsWchmhHFKylB8gx/ZWLFKnhjOJuE7N9lVcPtUrl+eoVIqaNlQe6hDkHdD6kwvGHRjVdZbYUI4aIkWdofHMzB43ngY8J/reWSh1b20pwlS1R+14nw7P80PNGQk6VsCo83nCeb6pdVnYza/6Lw3xYiNFEwnY8x7buysVsk517WHElbfNeMdPUf6UeVCsFKto7L9AeePgUJN9xGfrGH1qeHhCWKDIV4Cx6gOBTJCq+lBACDzqM7ChKjssUrWmap+DA6zAnR6Hf3/ojh89f8OZaKnfRxGlWCkg3SpJoRPv7Mzk9oCaEkONXuTyJ3OsxX6+KQrgD2vf9ou/tiJIS8Iq8TtFYr0jL8ElMTL/BWyiwwc7C+8gPrR2pnIOuf8O5F7qzIQcN4MITJoJxCUXB7nRQTyLjqSR8iEr0mqUzHipsTNMLtdGUd5SneCrPhoNlmvzFwRvHichiPA5LDjkEYV3XOIwJnsUYoYrjgH0bwHL3KQHu2lVp1T6ak7vDJ8cKyYIsZo/gamtBnq5F43iYtTEs8d6Sd+/HPAeZId/U3/6ZoOlJhd78vy0VT9eIMWUxSOxCZh675LoCSoRdemWNqZ8UJbQY1MAe14=
  - secure: pSKrTdijpmgQOBEo/6oXw7RVh9cXHw/fc00g1yULNE05vgoTwWjGC2AH97TscuHcV1+Mj7EOgeNr19V2xXu3C3MVjEQHaFu89kV3LuAWe2u79RU75WR2b/ik3N8zSRPnJRCD6BJ/V5tAIRM7swh4r1nNS+6mmtXUzyp7ZLKa8oI/xwWZRnK65AKESWTLj1Y19oupBAmTOrml1VwcLm1TLGoz0kFCn1pjEU8+dkMuaIJ0RREr1WWAw4fsvXK7JR3xp3lxbvYHhH4lrhgtbOnaiZSv+r94FXYqYHss29s0JQ8x26F/1XyIHWnBLyLleXNAP3QU+2HkYqNg4fiBCbi0eKEL7RYhxkgz7noknlw9SOeTUB4u2Eu86IxnQQ66HZCtpOx3qf8pAWkGjdQYVEPv3+r++dJwQCSgZPI2fM5u1auagebhVdOp3skS6LtReEJK/xQOrq37Xbj0kmUF22SH81chzMtdJ8LwU4P++hePtX39qyW9qhCRmfzj55mXVyYmmeQnbQJunOKJCQcfYRemjipqSa5y//xg/EXm3eyqxVdPmXJm9ztf2OmlMfuCPRJe/7cNW8u/IV2uRdeZfWK71Ok3V6hO4QKor5S2cCN16hUr7b0jBHZ24E1QugXu2KFNaPDpyBa6XB2WY/jW0YK96sFyZs7P51Rh0/Q0+0JFfys=
  email: false
